// Generated by LiveScript 1.5.0
var title;
if (location.pathname !== '/') {
  title = document.querySelector('article h1 a').textContent;
  document.querySelector('title').textContent = title + " - Kaihatsu";
}
hljs.initHighlightingOnLoad();